// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _requiredDefine(String key) {
    const missingValue = '';
    final value = String.fromEnvironment(key, defaultValue: missingValue);

    if (value == missingValue) {
      throw UnsupportedError(
        'Missing Dart define: $key. '
        'Create firebase_keys.json from firebase_keys.example.json '
        'and run with --dart-define-from-file=firebase_keys.json.',
      );
    }

    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_ANDROID_API_KEY'),
    appId: '1:496327021498:android:323b6e5307d197a8c98383',
    messagingSenderId: '496327021498',
    projectId: 'gerenciadorde-membros-fvlnpi',
    storageBucket: 'gerenciadorde-membros-fvlnpi.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_IOS_API_KEY'),
    appId: '1:496327021498:ios:33d015a94a8c0630c98383',
    messagingSenderId: '496327021498',
    projectId: 'gerenciadorde-membros-fvlnpi',
    storageBucket: 'gerenciadorde-membros-fvlnpi.firebasestorage.app',
    iosBundleId: 'com.bralves.grmembros',
  );
}
